name: tablet_reminder
description: "This is an app used for reminding patients to take tablets and notifies caregivers"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.10.4


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_3d_controller: ^2.3.0
  intl: ^0.20.2
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.3
  cloud_firestore: ^6.1.1
  google_sign_in: ^7.2.0
  sign_in_with_apple: ^7.0.1
  shared_preferences: ^2.5.4
  crypto: ^3.0.7
  url_launcher: ^6.3.2
  font_awesome_flutter: ^10.12.0
  modal_progress_hud_nsn: ^0.5.1
  animated_text_kit: ^4.3.0
  provider: ^6.1.5+1
  google_fonts: ^6.3.3
  vibration: ^3.1.5
  flutter_local_notifications: ^19.5.0
  timezone: ^0.10.1
  flutter_timezone: ^5.0.1
  firebase_messaging: ^16.1.0
  cloud_functions: ^6.0.5
  alarm: ^5.1.5
  pdf: ^3.11.3
  printing: ^5.14.2
  path_provider: ^2.1.5
  share_plus: ^12.0.1
  showcaseview: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/pill.png
    - assets/models/PillUpdatematrix.glb
    - assets/sounds/philippines-eas-alarm-427006.mp3
